openapi: 3.1.0
info:
  title: Search API
  version: latest
servers:
- url: /
paths:
  /_info:
    get:
      operationId: getServerInfo
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getServerInfo_200_response'
          description: Server information
      summary: Get server info
  /:
    post:
      description: Search with Query
      operationId: search
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Query'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
          description: Success
      summary: Search
      tags:
      - Search
components:
  schemas:
    Query:
      example:
        size: ""
        terms: ""
        ledgers: ""
        nextToken: ""
        target: ""
      properties:
        ledgers:
          items: {}
        nextToken: {}
        size: {}
        terms:
          items: {}
        target: {}
    Response:
      example:
        cursor:
          next: ""
          total:
            value: ""
            relation: ""
          previous: ""
          data: ""
          hasMore: ""
          pageSize: ""
        ledger: ""
        data: ""
        kind: ""
      properties:
        data:
          description: The payload
        cursor:
          $ref: '#/components/schemas/Response_cursor'
        kind:
          description: "The kind of the object, either \"TRANSACTION\" or \"META\""
        ledger:
          description: The ledger
    getServerInfo_200_response:
      example:
        version: ""
      properties:
        version: {}
    Response_cursor_total:
      example:
        value: ""
        relation: ""
      properties:
        value: {}
        relation: {}
    Response_cursor:
      example:
        next: ""
        total:
          value: ""
          relation: ""
        previous: ""
        data: ""
        hasMore: ""
        pageSize: ""
      properties:
        pageSize: {}
        hasMore: {}
        total:
          $ref: '#/components/schemas/Response_cursor_total'
        next: {}
        previous: {}
        data:
          items:
            allOf:
            - {}
